#export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
#export CUDA_HOME=/usr/local/cuda
#export LD_LIBRARY_PATH=/usr/local/cuda-10.1/lib64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/usr/local/cuda-10.0/lib64:$LD_LIBRARY_PATH
#export CUDA_HOME=/usr/local/cuda-10.1
export CUDA_HOME=/usr/local/cuda-10.0
export PRJ_ROOT=../..
#source $PRJ_ROOT/tools/venv/bin/activate
#source $PRJ_ROOT/tools/venv37/bin/activate
#source $PRJ_ROOT/tools/venv37pt1/bin/activate
#source $PRJ_ROOT/tools/venv37pt1cu10/bin/activate
#source $PRJ_ROOT/tools/venv37cu101v151/bin/activate
source $PRJ_ROOT/tools/venv37cu100v141/bin/activate
export PATH=$PATH:$PRJ_ROOT/src/bin:$PRJ_ROOT/src/utils
export PYTHONPATH=$PRJ_ROOT/src/nets:$PRJ_ROOT/src/utils
